### ISSUE TITLE
Do you have the datasets for this project?

### ISSUE THREAD

**Issue by zhiyu1998** [dleyan/STGAN#1]
I really can't find the relevant datasets. If you have the relevant datasets, can you upload it to your GitHub?

**Comment by dleyan** [comment]
The NYC dataset is provided by [https://www.microsoft.com/en-us/research/publication/detecting-collective-anomalies-from-multiple-spatio-temporal-datasets-across-different-domains/](url). And the BAY dataset is collected from [https://pems.dot.ca.gov/](url). I will update the BAY dataset used in our work to GitHub as soon as possible.
If you just need data for traffic flow prediction, you can refer to the following works.
1. [https://github.com/guoshnBJTU/ASTGNN](url)
2. [https://github.com/p0llx/DeepST-ResNet/tree/master/data/TaxiBJ](url) 
3. [https://github.com/liyaguang/DCRNN](url)

**Comment by zhiyu1998** [comment]
@dleyan That's awesome! Thank you for your timely help!!! lol

**Comment by zhiyu1998** [comment]
I have another question. On your work( load_data.py ), you use the
`graph_path = opt['data_path'] + '/node_subgraph.npy'     # (num_node, n, n), the subgraph of each node
adj_path = opt['data_path'] + '/node_adjacent.txt'     # (num_node, n), the adjacent of each node`
how can I translate the datasets (node_subgraph.npy、node_adjacent.txt) or download the datasets?
(ps. I have downloaded the datasets that you listed 11 days ago, but I haven't seen the datasets that I mention above. I am really sorry to have incommoded you. T_T) @dleyan

**Comment by dleyan** [comment]
I have uploaded the two datasets to Github.  The `node_subgraph.npy` and `node_adjacent.txt` for NYC dataset are translated according to the `data_description.pdf` and `NYC_862.txt` provided by (https://www.microsoft.com/en-us/research/publication/detecting-collective-anomalies-from-multiple-spatio-temporal-datasets-across-different-domains/). And the two files for PeMS dataset are translated according to the locations of sensors.

**Comment by zhiyu1998** [comment]
thx a lot, bro. I could close the issue finally~  lol @dleyan

**Comment by zhiyu1998** [comment]
oops, I find a data file that you did not upload it maybe. Just in load_data.py, I have run the code.
`dists = torch.tensor(np.loadtxt(self.opt['data_path'] + '/node_dist.txt'), dtype=torch.float)` ( in function weight )
I can't find ' node_dist.txt ' that describes two datasets are available at Google Drive in your README.md. I'm really sorry to bother you again.

**Comment by dleyan** [comment]
I have updated these two datasets.
