### ISSUE TITLE
a little question about bay dataset

### ISSUE THREAD

**Issue by fly-orange** [dleyan/STGAN#2]
It seems that in the bay dataset,  closet neighbours around each node selected according to distance provided in node_dist.npy are different from those in node_adjacent.npy.

**Comment by dleyan** [comment]
In bay dataset, the subgraph of each node is selected according to the connectivity. That is to say the two adjacent nodes are adjacent on a freeway with same direction. Note that we also consider the freeway intersection.

**Comment by fly-orange** [comment]
Thank you for your reply.

**Comment by fly-orange** [comment]
Sorry to bother yor again! I have another three questions:
(1)It seems that you delete some nodes according to some criterion when constructing datasets. For example, VDS 400014 is selected while its neighbour 402350 in the same freeway and direction are neglected. I want to know how you select nodes in the bay area. Maybe those node with missing values are neglected?
(2)When you construct graph about each node, you seem choose those nodes at its downstream as neighbour, thus leading to asymmetric adjacent matrix. Did you consider the causality other than correlation? Additionally, would you like to share the code to construct the graph regarding each node(node_subgraph.npy),  which may be a laborious work considering the intersaction.
(3)About the model, in the trend module, It seems that current values of all nodes in the subgraph are shared by only using the historical data of target node, which confuses me.
Thanks again for your open code and data!
