### ISSUE TITLE
Would you please share the anomaly labels of PeMS?

### ISSUE THREAD

**Issue by selchwang** [dleyan/STGAN#4]
Thanks for your work, as well as the code and data shared.
Would you please share the anomaly labels (including CHP Incident Report and LCS Report) of PeMS?

**Comment by dleyan** [comment]
We have updated the datasets at [Google Drive](https://drive.google.com/drive/folders/1U4ehoLEV83JLpPIXbopng0ydwfOAFLqN?usp=share_link). If you have any question about the data, please contact me by email ([dleyan@mail.ustc.edu.cn](mailto:dleyan@mail.ustc.edu.cn)).

**Comment by dleyan** [comment]
We have updated the datasets at [Google Drive](https://drive.google.com/drive/folders/1U4ehoLEV83JLpPIXbopng0ydwfOAFLqN?usp=share_link). If you have any question about the data, please contact me by email ([dleyan@mail.ustc.edu.cn](mailto:dleyan@mail.ustc.edu.cn)).
